# Generated by Django 6.0.3 on 2026-03-29 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique idempotency key from request header', max_length=255)),
                ('request_body', models.JSONField(help_text='The original request body for validation on retries')),
                ('response_body', models.JSONField(help_text='The cached response body to return on duplicate requests')),
                ('status_code', models.IntegerField(help_text='HTTP status code of the original response')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('processing_completed', models.BooleanField(default=False, help_text='Flag to handle race conditions (in-flight requests)')),
                ('user', models.ForeignKey(help_text='The user who made the payment request', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'key'], name='payment_gat_user_id_573e2c_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
